version: '3.9'
services:
  delivery-point-rating-ui:
    image: ghcr.io/theboys-4/delivery-point-rating-ui:main
    container_name: delivery-point-rating-ui
    ports:
      - '3000:3000'
    networks:
      - default_network
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  delivery-point-rating-gateway:
    image: ghcr.io/theboys-4/delivery-point-rating-gateway:main
    container_name: delivery-point-rating-gateway
    ports:
      - '80:9090'
      - '9090:9090'
    networks:
      - default_network
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  delivery-point-rating-data-service:
    image: ghcr.io/theboys-4/delivery-point-rating-data-service:main
    container_name: delivery-point-rating-data-service
    ports:
      - '8080:8080'
    networks:
      - default_network
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

#  delivery-point-rating-tg-bot:
#    image: ghcr.io/theboys-4/delivery-point-rating-tg-bot:main
#    container_name: delivery-point-rating-tg-bot
#    ports:
#      - '8081:8081'
#    networks:
#      - default_network
#    extra_hosts:
#      - 'host.docker.internal:172.17.0.1'

#  delivery-point-rating-data-processing-service:
#    image: ghcr.io/theboys-4/delivery-point-rating-data-processing-service:main
#    container_name: delivery-point-rating-data-processing-service
#    ports:
#      - '8082:8082'
#    networks:
#      - default_network
#    extra_hosts:
#      - 'host.docker.internal:172.17.0.1'

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - default_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3001:3000'
    networks:
      - default_network

networks:
  default_network:
    external: true
