version: '3.9'
services:

  delivery-point-rating-ui:
    image: ghcr.io/theboys-4/delivery-point-rating-ui:main
    container_name: delivery-point-rating-ui
    ports:
      - '80:3000'
    networks:
      - default_network
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  delivery-point-rating-data-service:
    image: savin0000/delivery-point-rating-data-service:main
    container_name: delivery-point-rating-data-service
    ports:
      - '8080:8080'
    networks:
      - default_network
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3001:3000'
    networks:
      - default_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - default_network

networks:
  default_network:
    external: true
