version: '3.9'
services:

  delivery-point-rating-ui:
    image: ghcr.io/theboys-4/delivery-point-rating-ui:main
    container_name: delivery-point-rating-ui
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    network_mode: host

  delivery-point-rating-data-service:
    image: savin0000/delivery-point-rating-data-service:main
    container_name: delivery-point-rating-data-service
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    network_mode: host

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    network_mode: host

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'

networks:
  default_network:
    external: true
